# Site Settings
title: Noverish Blog
email: embrapers273@gmail.com
description:  Noverish's iOS & Server development story blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://noverish.me" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Noverish's Blog
user_description: Korea University Junior, iOS & Server Developer
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: Noverish
facebook_username: facebook_username
twitter_username: Noverish

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
